api_book:
    type: rest
    resource: BookReviewBundle\Controller\ApiBookController
    name_prefix: api_book_
    prefix: /

api_review:
    type: rest
    resource: BookReviewBundle\Controller\ApiReviewController
    name_prefix: api_review_
    prefix: /

api_bookreview:
    type: rest
    resource: BookReviewBundle\Controller\ApiBookReviewController
    name_prefix: api_bookreview_
    parent:   api_book

api_user:
    type: rest
    resource: BookReviewBundle\Controller\ApiUserController
    name_prefix: api_user_
    prefix: /