book_index:
    path:     /
    defaults: { _controller: "BookReviewBundle:Book:index" }
    methods:  GET

book_show:
    path:     /{id}/show
    defaults: { _controller: "BookReviewBundle:Book:show" }
    methods:  GET

book_new:
    path:     /new
    defaults: { _controller: "BookReviewBundle:Book:new" }
    methods:  [GET, POST]

book_newpopulate:
    path:     /newpopulate
    defaults: { _controller: "BookReviewBundle:Book:newPopulate" }
    methods:  [GET, POST]

book_edit:
    path:     /{id}/edit
    defaults: { _controller: "BookReviewBundle:Book:edit" }
    methods:  [GET, POST]

book_delete:
    path:     /{id}/delete
    defaults: { _controller: "BookReviewBundle:Book:delete" }
    methods:  DELETE

book_review:
  path:     /{bookId}/review
  defaults: { _controller: "BookReviewBundle:Review:new" }
  methods:  [GET, POST]

book_find:
    path:     /find
    defaults: { _controller: "BookReviewBundle:Book:find" }
    methods:  [GET, POST]