api_index:
    path:     /
    defaults: { _controller: "BookReviewBundle:BookApi:talks" }
    methods:  GET

api_search_result:
    path:     /search
    defaults: { _controller: "BookReviewBundle:BookApi:search", page:1 }
    methods:  [GET, POST]

api_search_result:
    path:     /search/{value}&page={page}
    defaults: { _controller: "BookReviewBundle:BookApi:search", page:1 }
    methods:  GET


api_search_page:
    path:     /search/{value}
    defaults: { _controller: "BookReviewBundle:BookApi:search", page:1 }
    methods:  GET
