api_index:
    path:     /
    defaults: { _controller: "BookReviewBundle:BookApi:talks" }
    methods:  GET

api_search:
    path:     /search
    defaults: { _controller: "BookReviewBundle:BookApi:search", page:1 }
    methods:  [GET, POST]


api_details:
    path:     /details/{id}
    defaults: { _controller: "BookReviewBundle:BookApi:details", id:1 }
    methods:  [GET]