review_index:
    path:     /
    defaults: { _controller: "BookReviewBundle:Review:index" }
    methods:  GET

review_show:
    path:     /{id}/show
    defaults: { _controller: "BookReviewBundle:Review:show" }
    methods:  GET

review_new:
    path:     /new
    defaults: { _controller: "BookReviewBundle:Review:new" }
    methods:  [GET, POST]

review_edit:
    path:     /{id}/edit
    defaults: { _controller: "BookReviewBundle:Review:edit" }
    methods:  [GET, POST]

review_delete:
    path:     /{id}/delete
    defaults: { _controller: "BookReviewBundle:Review:delete" }
    methods:  DELETE
