

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

book_review_book:
    resource: "@BookReviewBundle/Controller/BookController.php"
    type:     annotation

book_review:
    resource: "@BookReviewBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

book_homepage:
    path:     /
    defaults: { _controller: "BookReviewBundle:Book:index" }