blogger_api:
    type: rest
    resource: "@BookReviewBundle/Resources/config/routing/api.yml"
    prefix: /api/v1

book_review_book:
    resource: "@BookReviewBundle/Controller/BookController.php"
    type:     annotation

book_review:
    resource: "@BookReviewBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

book_homepage:
    path:     /
    defaults: { _controller: "BookReviewBundle:Book:index" }

find:
    path:     /
    defaults: { _controller: "BookReviewBundle:Book:index" }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

