security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            oauth:
                # Declare the OAuth Callback URLs for every resource owner
                # They will be added in the routing.yml file too later
                resource_owners:
                    github: "/connect/check-github"
                ## Provide the original login path of your application (fosuserroute)
                ## and the failure route when the authentication fails.
                login_path:     /login
                failure_path:   /book
                # Inject a service that will be created in the step #6
                oauth_user_provider:
                    service: app.fos_user.oauth_provider
            anonymous:    ~
            logout:       ~

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/book/new, role: ROLE_USER}
        - { path: ^/book/[0-9]+/review, role: ROLE_USER}
        - { path: ^/book/[0-9]+/edit, role: ROLE_USER}

        - { path: ^/book/[0-9]+/delete, role: ROLE_MODERATOR}

        - { path: ^/review/new, role: ROLE_USER}
        - { path: ^/review/[0-9]+/edit, role: ROLE_USER}
        - { path: ^/review/[0-9]+/delete, role: ROLE_MODERATOR}

        - { path: ^/admin, role: ROLE_ADMIN}