# %kernel.root_dir%/serializer/FOSUB/Model.User.yml
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
            id:
                expose: true
            username:
                expose: true