book_review_book:
    resource: "@BookReviewBundle/Resources/config/routing/book.yml"
    prefix:   /book

book_review_review:
        resource: "@BookReviewBundle/Resources/config/routing/review.yml"
        prefix:   /review


book_user_api:
        resource: "@BookReviewBundle/Resources/config/routing/googleapi.yml"
        prefix:   /googleapi